src/Entity/Show.php
<?php

namespace App\Entity;

use App\Repository\ShowRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Doctrine\ORM\Mapping\JoinColumn;




#[ORM\Entity(repositoryClass: ShowRepository::class)]
#[ORM\Table(name: "shows")]
#[UniqueEntity(fields: ["slug"])]
class Show
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 60)]
    private ?string $slug = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $description = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $poster_url = null;

    #[ORM\ManyToOne(inversedBy: 'shows')]
    #[ORM\JoinColumn(onDelete: 'RESTRICT')]
    private ?Location $location = null;

    #[ORM\Column]
    private ?bool $bookable = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 12, scale: 2, nullable: true)]
    private ?string $price = null;

    #[ORM\OneToMany(mappedBy: 'the_show', targetEntity: Representation::class, orphanRemoval: true)]
    private Collection $representations;

    #[ORM\ManyToMany(targetEntity: ArtistType::class, inversedBy: 'shows')]
    private Collection $artistTypes;

    public function __construct()
    {
        $this->representations = new ArrayCollection();
        $this->artistTypes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPosterUrl(): ?string
    {
        return $this->poster_url;
    }

    public function setPosterUrl(?string $poster_url): self
    {
        $this->poster_url = $poster_url;

        return $this;
    }

    public function getLocation(): ?Location
    {
        return $this->location;
    }

    public function setLocation(?Location $location): self
    {
        $this->location = $location;

        return $this;
    }

    public function isBookable(): ?bool
    {
        return $this->bookable;
    }

    public function setBookable(bool $bookable): self
    {
        $this->bookable = $bookable;

        return $this;
    }

    public function getPrice(): ?string
    {
        return $this->price;
    }

    public function setPrice(?string $price): self
    {
        $this->price = $price;

        return $this;
    }

    /**
     * @return Collection<int, Representation>
     */
    public function getRepresentations(): Collection
    {
        return $this->representations;
    }

    public function addRepresention(Representation $represention): self
    {
        if (!$this->representations->contains($represention)) {
            $this->representations->add($represention);
            $represention->setTheShow($this);
        }

        return $this;
    }

    public function removeRepresention(Representation $represention): self
    {
        if ($this->representations->removeElement($represention)) {
            // set the owning side to null (unless already changed)
            if ($represention->getTheShow() === $this) {
                $represention->setTheShow(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, ArtistType>
     */
    public function getArtistTypes(): Collection
    {
        return $this->artistTypes;
    }

    public function addArtistType(ArtistType $artistType): self
    {
        if (!$this->artistTypes->contains($artistType)) {
            $this->artistTypes->add($artistType);
        }

        return $this;
    }

    public function removeArtistType(ArtistType $artistType): self
    {
        $this->artistTypes->removeElement($artistType);

        return $this;
    }


    public function getAuthors(): Collection
    {
        $authors = new ArrayCollection();

        foreach ($this->artistTypes as $collaboration) {
            if ($collaboration->getArtistType($collaboration->getArtist())->getType() == "scénographe") {
                $authors->add($collaboration->getArtist());
            }
        }

        return $authors;
    }
}

src/Controller/ShowController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\Show;
use App\Repository\ShowRepository;

#[Route('/show')]

class ShowController extends AbstractController

{#[Route('/', name:'show_index', methods: ['GET'])]
    public function index(ShowRepository $repository): Response
    {
        $shows = $repository->findAll();
       

        return $this->render('show/index.html.twig', [
            'shows' => $shows,
            'resource' => 'Liste des spectacles',
        ]);

    }  
    
    #[Route('/{id}', name:'show_show', methods: ['GET'])]
    public function show(int $id, ShowRepository $repository): Response
    {
       
        $show = $repository->find($id);

        //Récupérer les artistes du spectacle et les grouper par type
        $collaborateurs = [];

        foreach($show->getArtistTypes() as $at) {
            $collaborateurs[$at->getType()->getType()][] = $at->getArtist();
        }


        return $this->render('show/show.html.twig', [
            'show' => $show,
            'collaborateurs' => $collaborateurs,
        ]);
    }
}

templates/show/index.html.twig
{% extends 'base.html.twig' %} 
{% block title %}{{ resource }}{% endblock %} 

{% block body %} 
    {% include 'includes/header.html.twig' %}
    <link rel="stylesheet" type="text/css" href="{{ asset('asset/css/datatables.css') }}" />

    <script>
        $(document).ready(function () {
            $("#table_shows").DataTable();
        });
    </script>

    {% include 'includes/menu.html.twig' %}

    <div class="wrapper">
        <h1>{{ resource }}</h1>

        <table id="table_shows">
            <thead>
                <tr>
                    <th>Titre</th>
                    <th>Auteur</th>
                    <th>Lieu</th>
                    <th>Représentations</th>
                    <th>Prix</th>
                    <th>Réservable</th>
                    <th>Description</th>
                </tr>
            </thead>
            <tbody>
                {% for show in shows %}
                    <tr>
                        <td>
                            {{ show.title | title }}
                        </td>
                        <td>
                            {% for author in show.authors %}
                                {{ author.firstname }}&nbsp;{{ author.lastname }}
                            {% endfor %}
                        </td>
                        <td>{{ show.location ? show.location.designation : "No location" }}</td>
                        <td>{{ show.representations | length }}</td>
                        <td>{{ show.price|number_format(2, ',', '.') }}&nbsp;&euro;</td>
                        {% if show.bookable %}
                            <td>Oui</td>
                        {% else %}
                            <td>Non</td>
                        {% endif %}
                        <td>
                            <a href="{{ path('show_show', {'id': show.id}) }}" class="btn btn-primary">
                                Voir
                            </a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
            
        </table>

        <p>Total: {{ shows | length }} spectacles.</p>
    </div>

    {% include 'includes/footer.html.twig' %}
{% endblock %}

templates/show/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Fiche d'un spectacle{% endblock %}

{% block body %}
    <article>
        <h1>{{ show.title }}</h1>

        {% if show.posterUrl %}
        <p><img src="{{ asset(show.getposterUrl()) }}" alt="{{ show.title }}" width="200"></p>
        {% else %}
        <canvas width="200" height="100" style="border:1px solid #000000;"></canvas>
        {% endif %}

        {% if show.location %}
        <p><strong>Lieu de création:</strong> {{ show.location.designation }}</p>
        {% endif %}
        
       <p><strong>Prix:</strong> {{ show.price }} €</p>

        {% if show.bookable %}
        <p><em>Réservable</em></p>
        {% else %}
        <p><em>Non réservable</em></p>
        {% endif %}
    </article>

           <h2>Liste des représentations</h2>
        {% if show.representations|length>=1 %}
        <ul>
            {% for representation in show.representations %}
                <li>{{ representation.schedule|date('d/m/Y G:i:s') }}</li>              
            {% endfor %}
        </ul>
        {% else %}
        <p>Aucune représentation</p>
        {% endif %}
        
        <h2>Liste des artistes</h2>
        <p><strong>Auteur:</strong>
        {% for auteur in collaborateurs['auteur'] %}
            {{ auteur.firstname }} 
            {{ auteur.lastname }}{% if loop.index == loop.length-1 %} et 
            {% elseif not loop.last %}, {% endif %}
        {% endfor %}
        </p>
        <p><strong>Metteur en scène:</strong>
        {% for scenographe in collaborateurs['scénographe'] %}
            {{ scenographe.firstname }} 
            {{ scenographe.lastname }}{% if loop.index == loop.length-1 %} et 
            {% elseif not loop.last %}, {% endif %}
        {% endfor %}
        </p>
        <p><strong>Distribution:</strong>
        {% for comedien in collaborateurs['comédien'] %}
            {{ comedien.firstname }} 
            {{ comedien.lastname }}{% if loop.index == loop.length-1 %} et 
            {% elseif not loop.last %}, {% endif %}
        {% endfor %}
        </p>



    <nav><a href="{{ path('show_index') }}">Retour à l'index</a></nav>
    
{% endblock %}